### ISSUE TITLE
prediction visualization

### ISSUE THREAD

**Issue by wenlilong** [FactoDeepLearning/SPAN#1]
Could you provide the codes about hot to visualize prediction results.
![Capture](https://user-images.githubusercontent.com/8676126/120919743-c5063800-c6ed-11eb-87a0-27cfa50c9bba.PNG)

**Comment by FactoDeepLearning** [comment]
I don't have clean code for this. In brief, a tensor is created with same shape as features, all non-blank predictions are set to 1 (red), else 0 (transparency). And this tensor is projected to the input image with matplotlib using the extent. Text has been manually added to the right side.

**Comment by wenlilong** [comment]
> I don't have clean code for this. In brief, a tensor is created with same shape as features, all non-blank predictions are set to 1 (red), else 0 (transparency). And this tensor is projected to the input image with matplotlib using the extent. Text has been manually added to the right side.

Thank you very much for your reply

**Comment by AlxJude** [comment]
@ll-wen Hello, were you able to produce the visualization of the inference? If yes, could you please guide me?
I have one image which is not part of any dataset which I want to do a model prediction on.
