### ISSUE TITLE
Slicing in training

### ISSUE THREAD

**Issue by Sonel-YXL** [FactoDeepLearning/SPAN#11]
Thank you very much for your excellent work！
When I studied your code in depth recently, I didn't quite understand the line of code (pred = global_pred[i, :, :x_h, :x_w]) in function train_batch. Why do you do this？

**Comment by Sonel-YXL** [comment]
Do you think this is correct?
After the image passes the SPAN network, the h and w of the obtained tensor (b, c, h, w) have slight changes, and some information on the edge of the feature map is discarded.

**Comment by Sonel-YXL** [comment]
Batch images process each image to the same size. Slicing is to restore a single image in the batch image, is right?

**Comment by FactoDeepLearning** [comment]
You are right, the aim is to retrieve the prediction of the original image, discarding the padding part.

**Comment by Sonel-YXL** [comment]
Your help was very much appreciated. I just have one more question for you.
If the text is close to the edge, will there be any error? After debugging, the batch image shape is (2,91,13,165). After slicing, the size of each feature map is (11,164), (12,123). There is an error of 1 unit between the trimmed h and w and the original batch feature map, for example: x_ h=12 and h=13, x_ w=164 and w=165.

**Comment by FactoDeepLearning** [comment]
This must be a delta from the pooling or strided convolution operation. Considering the large receptive field, and that the model is trained on the same conditions as during evaluation, I do not think this has a significant impact. I did not notice this kind of errors through experiments.

**Comment by Sonel-YXL** [comment]
it's really  appreciated. It is very helpful to my work.
