### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sonel-YXL** [FactoDeepLearning/SPAN#4]
Thank you for your excellent work (van and span) When I reproduce the code, why are many characters predicted to be len (self. Charset) in my data set

**Comment by FactoDeepLearning** [comment]
Hello, it corresponds to the additional blank (null) token used by the CTC loss

**Comment by yxl765189898** [comment]
Thank you so much. Another question is that for predicted characters, many are predicted blank characters. Is this a normal phenomenon? I applied your work to Tibetan dataset .Tibetan is a two - dimensional structure, like "བྱས་པ་དང་འབྲེལ" Can the network work well on this data set?

**Comment by FactoDeepLearning** [comment]
Yes, this is a common behavior. SPAN will work for text whose reading order is from top to bottom and left to right (single column of text). If this is not the case, it would need some modification on the reshaping operation.

**Comment by Sonel-YXL** [comment]
Thank you very much. This research is really great
